---
title: "datamerging"
author: "Suheng Yao"
date: "2024-11-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggmap)
library(sf)
library(gridExtra)
library(plotly)
library(lubridate)
library(ggcorrplot)
```

```{r}
df <- read.csv("../data/fires_range(in).csv")
PHLI <- read.csv("../data/PHLI.2020-12-31.csv")
POPH1 <- read.csv("../data/POPH1.2024-11-22.csv")
PLRH1 <- read.csv("../data/PLRH1.2024-11-22.csv")
WHGH1 <- read.csv("../data/WHGH1.2020-12-31.csv")
MKAH1 <- read.csv("../data/MKAH1.2024-11-22.csv")
```

```{r}
df <- head(df, -1)
df <- df %>%
  select(-location) %>%
  arrange(desc(acres))
df$closest_station <- c("POPH1", "PLRH1", "WHGH1", "PHLI", "WHGH1", 
                        "MKAH1", "WHGH1")
```
```{r}
filter_data_by_date_range <- function(data, start_date, end_date) {
  data <- data %>%
    mutate(Date_Time = as.POSIXct(Date_Time, 
                                  format = "%Y-%m-%dT%H:%M:%OSZ", 
                                  tz = "UTC"))
  start_date <- as.POSIXct(start_date, tz = "UTC")
  end_date <- as.POSIXct(end_date, tz = "UTC")
  
  filtered_data <- data %>%
    filter(Date_Time >= start_date & Date_Time <= end_date)
  if(start_date == end_date){
    filtered_data <- data %>%
    filter(as.Date(Date_Time) == as.Date(start_date))
  }
  
  return(filtered_data)
}

id3_fire <- filter_data_by_date_range(POPH1, "2012-08-07", "2012-08-23")
id2_fire <- filter_data_by_date_range(PLRH1, "2012-06-15", "2012-07-05")
id6_fire <- filter_data_by_date_range(WHGH1, "2017-04-24", "2017-05-19")
id7_fire <- filter_data_by_date_range(PHLI, "2019-06-01", "2019-06-13")
id5_fire <- filter_data_by_date_range(WHGH1, "2015-05-25", "2015-06-10")
id1_fire <- filter_data_by_date_range(MKAH1, "2012-05-18", "2012-06-06")
id4_fire <- filter_data_by_date_range(WHGH1, "2015-03-13", "2015-03-23")
id3_fire <- id3_fire %>% mutate(ID = 3)
id2_fire <- id2_fire %>% mutate(ID = 2)
id6_fire <- id6_fire %>% mutate(ID = 6)
id7_fire <- id7_fire %>% mutate(ID = 7)
id5_fire <- id5_fire %>% mutate(ID = 5)
id1_fire <- id1_fire %>% mutate(ID = 1)
id4_fire <- id4_fire %>% mutate(ID = 4)
all_weather_data <- bind_rows(id3_fire, id2_fire, id6_fire, 
                              id7_fire, id5_fire, id1_fire, id4_fire)
df <- left_join(all_weather_data, df, by="ID")
df <- df %>%
  rename(fire_event_ID = ID) %>%
  select(fire_event_ID, everything())
```
```{r}
colSums(is.na(df))
```
```{r}
df <- df[, colSums(is.na(df)) < 3000]
colSums(is.na(df))
```
```{r}
# write_csv(df, "../data/final_data.csv")
```

```{r}
register_google(key = "AIzaSyBZLfJLv6FbqwjkkzLNeVt3H5LO35g0v20")

base_map <- get_map(location = c(lon = -159.55, lat = 22.05), zoom = 11, maptype = "terrain")

specific_location <- df %>%
  distinct(lattitude, longitude)

# Plot the data on the map
ggmap(base_map) +
  geom_point(aes(x = longitude, y = lattitude), data = specific_location, color = "red", size = 3) +
  labs(title = "Fire Events", x = "Longitude", y = "Latitude")
```

# EDA
## Calculate the Monthly Mean Temperature for Five Years Before Each Fire Event
```{r}
MKAH1_5 <- MKAH1 %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2007 & year(Date_Time) <= 2011, # Filter years between 2007 and 2012
         month(Date_Time) == 5) # Filter only for May

PLRH1_6 <- PLRH1 %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2007 & year(Date_Time) <= 2011,
         month(Date_Time) == 6)

POPH1_8 <- POPH1 %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2007 & year(Date_Time) <= 2011,
         month(Date_Time) == 8)

WHGH1_3 <- WHGH1 %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2010 & year(Date_Time) <= 2014,
         month(Date_Time) == 3)

WHGH1_6 <- WHGH1 %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2010 & year(Date_Time) <= 2014,
         month(Date_Time) == 6)

WHGH1_5 <- WHGH1 %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2012 & year(Date_Time) <= 2016,
         month(Date_Time) == 5)

PHLI_6 <- PHLI %>%
  mutate(Date_Time = as.POSIXct(Date_Time, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")) %>% # Convert to POSIXct
  filter(year(Date_Time) >= 2014 & year(Date_Time) <= 2018,
         month(Date_Time) == 6)
```

```{r}
datasets <- list(MKAH1_5, PLRH1_6, POPH1_8, WHGH1_3, WHGH1_6, WHGH1_5, PHLI_6)
avg_temp <- sapply(datasets, function(data) mean(data$air_temp_set_1, na.rm = TRUE))
  
for (i in c(1:7)) {
  id_temp <- df %>%
    filter(fire_event_ID == i)

  p <- ggplot(id_temp, aes(x = Date_Time, y = air_temp_set_1)) +
          geom_line(size = 1) +
          geom_hline(yintercept = avg_temp[i], color = "blue", linetype = "dashed", linewidth = 0.8) +
          labs(title = paste("Temperature for Fire Event", i),
               x = "Date Time",
               y = "Temperature") +
          theme_minimal()
  ggsave(filename = paste0("www/Temperature", i, ".png"), plot = p, width = 8, height = 6)
}
```

```{r}
avg_humid <- sapply(datasets, function(data) mean(data$relative_humidity_set_1, na.rm = TRUE))
for (i in c(1:7)) {
  id_temp <- df %>%
    filter(fire_event_ID == i)

  p <- ggplot(id_temp, aes(x = Date_Time, y = relative_humidity_set_1)) +
          geom_line(linewidth = 1) +
          geom_hline(yintercept = avg_humid[i], color = "blue", linetype = "dashed", size = 0.8)+
          labs(title = paste("Relative Humidity for Fire Event", i),
               x = "Date Time",
               y = "Humidity") +
          theme_minimal()
  ggsave(filename = paste0("www/Humidity", i, ".png"), plot = p, width = 8, height = 6)
}
```

```{r}
avg_wind <- sapply(datasets, function(data) mean(data$wind_speed_set_1, na.rm = TRUE))
for (i in c(1:7)) {
  id_temp <- df %>%
    filter(fire_event_ID == i)

  p <- ggplot(id_temp, aes(x = Date_Time, y = wind_speed_set_1)) +
          geom_line(size = 1) +
          geom_hline(yintercept = avg_wind[i], color = "blue", linetype = "dashed", linewidth = 0.8)+
          labs(title = paste("Wind Speed for Fire Event", i),
               x = "Date Time",
               y = "Speed") +
          theme_minimal()
  ggsave(filename = paste0("www/WindSpeed", i, ".png"), plot = p, width = 8, height = 6)
}
```

```{r}
df$fire_event_ID <- as.factor(df$fire_event_ID)
numeric_df <- df %>%
  select(where(is.numeric))

# Compute the correlation matrix
correlation_matrix <- cor(numeric_df, use = "pairwise.complete.obs")

# Visualize the correlation matrix
cor_plot <- ggcorrplot(correlation_matrix,
           type = "lower",
           lab = TRUE,
           lab_size = 2, 
           colors = c("#6D9EC1", "white", "#E46726"),
           title = "Correlation Matrix of Weather Variables",
           tl.cex = 8,
           tl.srt = 45)
ggsave(
  filename = "www/correlationplot.png", # Replace with your folder path
  plot = cor_plot,
  width = 8,   
  height = 6
)
```
```{r}
df_selected <- df %>%
  select(-c(fire_event_ID, Station_ID, Date_Time, start_date, end_date, closest_station, pressure_change_code_set_1, lattitude, longitude, metar_set_1, weather_condition_set_1d, pressure_set_1d))

df_selected$sea_level_pressure_set_1d <- as.numeric(df_selected$sea_level_pressure_set_1d)

df_selected <- df_selected %>%
  mutate(across(where(is.character), as.factor))

df_selected <- df_selected[, colSums(is.na(df_selected)) < 1000]
df_selected <- na.omit(df_selected)

model1 <- lm(acres~., data = df_selected)
summary(model1)
plot(model1)
```
```{r}
model2 <- lm(acres~air_temp_set_1+wind_speed_set_1+wind_direction_set_1+dew_point_temperature_set_1d, data = df_selected)
summary(model2)
```
```{r}
model3 <- lm(acres~air_temp_set_1+wind_direction_set_1+wind_speed_set_1, data = df_selected)
summary(model3)
```
```{r}
model0 <- lm(acres~1, data = df_selected)
summary(model0)
```

```{r}
predictions <- predict(model0, type = "response")
mse <- mean((df_selected$acres - predictions)^2)
print(mse)

predictions <- predict(model1, type = "response")
mse <- mean((df_selected$acres - predictions)^2)
print(mse)

predictions <- predict(model2, type = "response")
mse <- mean((df_selected$acres - predictions)^2)
print(mse)

predictions <- predict(model3, type = "response")
mse <- mean((df_selected$acres - predictions)^2)
print(mse)
```
model1 gives us the best results, which means that the important predictors are air temperature, wind direction and dew point temperature.

Use xgboost to verify the results:
```{r}
# Load necessary library
library(xgboost)


# Prepare data
x <- model.matrix(acres ~ . - 1, data = df_selected)  # Create design matrix
y <- df_selected$acres

# Train XGBoost model
xgb_model <- xgboost(data = x, label = y, nrounds = 100, objective = "reg:squarederror")

# Feature importance
importance_matrix <- xgb.importance(feature_names = colnames(x), model = xgb_model)
xgb.plot.importance(importance_matrix)
```



