---
title: "dataanalysis"
author: "Suheng Yao"
date: "2024-10-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

```{r, message=FALSE}
library(dplyr)
# Read in the data
df <- read.csv("data/HI_State_Ignitions_All.csv")

# Only select data associated with Kauai
df <- df %>%
  filter(County == "Kauai")
```
```{r}
df$Date <- paste(df$Year, df$Month, df$Day, sep = "-")
df <- df[, !names(df) %in% c("Day", "Month", "Year")]
df <- df[, c("Date", setdiff(names(df), "Date"))]
df$Date <- as.Date(df$Date, format = "%Y-%m-%d")
df$Date <- df$Date - 1
```
```{r}
write.csv(df, "data/Kauai Data.csv", row.names = FALSE)
```
```{r, warning=FALSE}
# Read the first row (variable names)
headers <- read.csv("data/PHBK.2020-12-31.csv", nrows = 1, header = FALSE)
# Read the second row (units)
units <- read.csv("data/PHBK.2020-12-31.csv", skip = 1, nrows = 1, header = FALSE)

# Combine headers and units
new_headers <- paste(headers, "(", units, ")")

# Read the actual data with new combined headers
df_phbk <- read.csv("data/PHBK.2020-12-31.csv", skip = 2, col.names = new_headers)
```
```{r}
glimpse(df_phbk)
colSums(is.na(df_phbk))
```

## Start Data Cleaning
```{r, warning=FALSE}
df_phbk$sea_level_pressure_set_1d...Pascals.. <- as.numeric(df_phbk$sea_level_pressure_set_1d...Pascals..)

df_phbk$Date_Time...NA.. <- as.POSIXct(df_phbk$Date_Time...NA.., format="%Y-%m-%dT%H:%M:%SZ")

# Remove the columns with more than 100,000 NA values
df_phbk <- df_phbk[, colSums(is.na(df_phbk)) < 100000]
```

```{r}
# Merge the df and df_phbk
# First make the date in the same format
df_phbk$Date_Time...NA.. <- as.Date(df_phbk$Date_Time...NA..)
df_phbk <- df_phbk %>%
  rename(Date=Date_Time...NA..)
# Merge based on date
merge_df <- merge(df, df_phbk, by="Date", all=FALSE)
```
```{r}
merge_df <- merge_df %>%
  filter(!is.na(air_temp_set_1...Celsius..))

ggplot(merge_df, aes(x=Date, y=air_temp_set_1...Celsius..))+
  geom_line()+
  theme_minimal()
```
```{r}
merge1 <- merge_df %>%
  filter((air_temp_set_1...Celsius.. < -10) | 
           (air_temp_set_1...Celsius.. > 40))
```

# find data in other stations, find possible missing pattern, find meaning of each variable